# Generated by Django 2.0.7 on 2021-03-04 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comments',
            table='comments',
        ),
        migrations.AlterModelTable(
            name='posts',
            table='posts',
        ),
    ]
