# Generated by Django 2.0.7 on 2021-03-12 14:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_auto_20210305_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='categorie_name',
            field=models.CharField(default='None', max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
