# Generated by Django 2.0.7 on 2021-03-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_auto_20210312_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='email',
            field=models.CharField(default='None', max_length=220),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.CharField(default='None', max_length=220),
        ),
    ]
